from __future__ import annotations

from collections.abc import Iterator
from typing import Protocol, runtime_checkable

from kochab.contracts.models import (
    Change,
    EvalResult,
    SuiteInfo,
    SurfaceManifest,
    Trace,
    TraceFilter,
    TraceRef,
    Version,
)


@runtime_checkable
class TuningSurface(Protocol):
    def manifest(self) -> SurfaceManifest: ...
    def read(self, unit_id: str) -> str: ...
    def apply(self, change: Change) -> Version: ...
    def rollback(self, to: Version) -> None: ...
    def diff(self, a: Version, b: Version) -> str: ...
    def baseline(self) -> Version: ...
    def accepted(self) -> Version: ...
    def mark_accepted(self, version: Version) -> Version: ...
    def restore_accepted(self) -> Version: ...


@runtime_checkable
class EvalPort(Protocol):
    def suites(self) -> list[SuiteInfo]: ...
    def criteria(self) -> str: ...
    def gold(self, case_id: str) -> str | None: ...
    def run(
        self,
        case_ids: list[str],
        surface_version: Version,
        visibility: str = "train",
    ) -> EvalResult: ...


@runtime_checkable
class TracePort(Protocol):
    def query(self, filter: TraceFilter) -> list[TraceRef]: ...
    def read(self, ref: TraceRef) -> Trace: ...
    def subscribe(self, filter: TraceFilter) -> Iterator[TraceRef]: ...
